server:
  port: 8000

spring:
  application:
    name: BookMarky
    devtools:
      livereload:
        enabled: true

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

  props:
    reset-password-url: 127.0.0.1:8080/pw

  profiles:
    active: private # DB, SMTP 정보 숨김