server:
  port: 8000

spring:
  application:
    name: BookMarky
    devtools:
      livereload:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: db # db 정보 숨김

  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: bookmarky24@gmail.com
    password: r d f c w m k w s i ro i g v b
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: true

  props:
    reset-password-url: 127.0.0.1:8080/pw