server:
  port: 8000

spring:
  application:
    name: BookMarky
    devtools:
      livereload:
        enabled: true

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show-sql: true
        format-sql: true

  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: private # DB, SMTP, 계정 정보 숨김