server:
  port: 8000

spring:
  application:
    name: BookMarky

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  profiles:
    active: private # MySQL, Redis, MAIL, SMTP 연결 정보 숨김