server:
  port: 8000

spring:
  application:
    name: BookMarky

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  profiles:
    active: private # DB, MAIL, SMTP 연결 정보 숨김